In [1]:
l=[32123,1234,23,13241,-231]

In [2]:
l

[32123, 1234, 23, 13241, -231]

In [3]:
import numpy as np

In [4]:
a=np.array(l)

In [5]:
a

array([32123,  1234,    23, 13241,  -231])

In [6]:
b=np.array([12,124,124354234,True,'adfq'])

In [7]:
b

array(['12', '124', '124354234', 'True', 'adfq'], dtype='<U21')

In [8]:
a.mean()

9278.0

In [9]:
a.max()

32123

In [10]:
l[0:2]

[32123, 1234]

---

In [11]:
a

array([32123,  1234,    23, 13241,  -231])

In [12]:
a[2:]

array([   23, 13241,  -231])

In [13]:
a[2:4]

array([   23, 13241])

In [14]:
b=a[2:4]

In [15]:
b

array([   23, 13241])

In [16]:
b[:]=111

In [17]:
b

array([111, 111])

In [18]:
a

array([32123,  1234,   111,   111,  -231])